---
version: "2.1"
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /mnt/smokeping_storage/smokeping/config:/config
      - /mnt/smokeping_storage/smokeping/data:/data
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
